FROM oven/bun:1

WORKDIR /app

# Nota: El archivo se llama bun.lockb (con 'b' al final)
COPY package.json bun.lock ./ 
RUN bun install --frozen-lockfile

COPY . .

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start"]
